timeline
    title History of Social Media Platforms
    section Early Web
        2002 : LinkedIn
        2003 : MySpace
    section Social Era
        2004 : Facebook
             : Google
        2005 : Youtube
        2006 : Twitter
    section Mobile Era
        2010 : Instagram
        2011 : Snapchat
