journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Lunch break
      Eat lunch: 4: Me
      Take a walk: 4: Me
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
